###Testing POST functionality
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "Dune",
    "author": "Frank Herbert",
    "isbn": "9780441013593"
}

###GET Books
GET Http://localhost:3000/api/books

###Update book with PUT
PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
    "name": "Dune Messiah",
    "author": "Frant Herbert",
    "isbn": "9780441172696"
}

###Delete book
DELETE http://localhost:3000/api/books/1

###POST Borrower
POST http://localhost:3000/api/borrowers
Content-Type: application/json

{
    "fname": "Joonas",
    "lname": "Testi",
    "streetAddress": "Katu123"
}

###GET Borrowers
GET Http://localhost:3000/api/borrowers

###Update borrowers with PUT
PUT http://localhost:3000/api/borrowers/1
Content-Type: application/json

{
    "fname": "Nimi",
    "lname": "Testaus",
    "streetAddress": "Katu312"
}

###Delete borrower
DELETE http://localhost:3000/api/borrowers/1

###Opiskelijat POST
POST http://localhost:3000/api/opiskelijat
Content-Type: application/json

{
  "Etunimi": "Testi",
  "Sukunimi": "Opiskelija",
  "Osoite": "Testikatu 1",
  "Luokkatunnus": "TVT25SP"
}
###GET
GET http://localhost:3000/api/opiskelijat

###PUT
PUT http://localhost:3000/api/opiskelijat/1
Content-Type: application/json

{
  "Etunimi": "Hannu",
  "Sukunimi": "Ankka",
  "Osoite": "Ankkalinna 999",
  "Luokkatunnus": "TVT25SP"
}

###DELETE
DELETE http://localhost:3000/api/opiskelijat/1

###Same thing for Opintojakso
###POST
POST http://localhost:3000/api/opintojaksot
Content-Type: application/json

{
  "Koodi": "T12321",
  "Laajuus": 3,
  "Nimi": "Testikurssi"
}

###GET
GET http://localhost:3000/api/opintojaksot

###PUT
PUT http://localhost:3000/api/opintojaksot/1
Content-Type: application/json

{
  "Koodi": "T20041",
  "Laajuus": 5,
  "Nimi": "Tietokannat Testi"
}

###DELETE
DELETE http://localhost:3000/api/opintojaksot/9

###Same for arviointi
###POST
POST http://localhost:3000/api/arvioinnit
Content-Type: application/json

{
  "Paivamaara": "2026-03-08",
  "Arvosana": 4,
  "idOpintojakso": 1,
  "idOpiskelija": 7
}

###GET
GET http://localhost:3000/api/arvioinnit

###PUT
PUT http://localhost:3000/api/arvioinnit/15
Content-Type: application/json

{
  "Paivamaara": "2026-03-08",
  "Arvosana": 5,
  "idOpintojakso": 1,
  "idOpiskelija": 7
}

###DELETE
DELETE http://localhost:3000/api/arvioinnit/15

###Testing encryption
###POST

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "joonaskoivula",
    "password": "password123"
}

###GET
GET http://localhost:3000/api/users
